version: "2.2"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: cfiddle-slurm:21.08.6.1
    build:
      context: .
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: cfiddle-slurm:21.08.6.1
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  c1:
    image: cfiddle-slurm:21.08.6.1
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    privileged: True
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /home/swanson/CSE141pp-Root
        target: /cse142L
      - type: bind
        source: /home
        target: /home
      - type: bind
        source: ${HOME}
        target: /root
      - cfiddle_scratch:/cfiddle_scratch
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: cfiddle-slurm:21.08.6.1
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    privileged: True
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ${HOME}
        target: /root
      - type: bind
        source: /home
        target: /home
      - type: bind
        source: /home/swanson/CSE141pp-Root
        target: /cse142L
      - cfiddle_scratch:/cfiddle_scratch
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  cfiddle-dev:
    image: cfiddle-slurm:21.08.6.1
    command: ["slurmd"]
    hostname: cfiddle-dev
    container_name: cfiddle-dev
    privileged: True
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /home/swanson/CSE141pp-Root
        target: /cse142L
      - type: bind
        source: ${HOME}
        target: /root
      - type: bind
        source: /home
        target: /home
      - cfiddle_scratch:/cfiddle_scratch

    expose:
      - "8888"
    depends_on:
      - "slurmctld"
   
volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  cfiddle_venv:
  cfiddle_scratch:
